#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 640

#define TOP_FIELD_BORDER 50
#define BOTTOM_FIELD_BORDER 575
#define LEFT_FIELD_BORDER 200
#define RIGHT_FIELD_BORDER 425

#define FIELD_WIDTH 10
#define FIELD_HEIGHT 20

#define BLOCK_SIZE 25

#define BLOCKS_COUNT 4

#define MOVING_DOWN_INTERVAL 100

#define SINGLE "SINGLE"
#define DOUBLE "DOUBLE"
#define TRIPLE "TRIPLE"
#define TETRIS "TETRIS"